version: '3.3'

services:
  database:
    image: postgres
    container_name: news_database
    restart: unless-stopped
    volumes:
      - news_database:/var/lib/postgresql/data
    ports:
    - 5432:5432
    env_file:
        - database.env
    networks:
      - backend

  newscollector:
    build: newscollector
    image: newscollector:latest
    restart: unless-stopped
    container_name: news_collector
    networks:
      - backend
    depends_on:
      - database

volumes:
  news_database:
    external: true

networks:
  backend:
    driver: bridge
